local SI_ACTIVE_ROUTES = {
    {
        name = "si_sgi_directed";
        source = "si_cpu.icc_sgi1r_el1";
        controller = "si_cl0_gic";
        kind = "SGI";
        architectural_intid = 5;
        socket_class = "sgi";
        socket_index = 5;
        trigger = "edge";
        polarity = "none";
        owner_view = "View1";
        target_semantics = "directed";
        target_pes = {4};
    };
    {
        name = "si_sgi_broadcast";
        source = "si_cpu.icc_sgi1r_el1_irm";
        controller = "si_cl0_gic";
        kind = "SGI";
        architectural_intid = 6;
        socket_class = "sgi";
        socket_index = 6;
        trigger = "edge";
        polarity = "none";
        owner_view = "View1";
        target_semantics = "broadcast";
        target_pes = {1, 2, 3, 4};
    };
    {
        name = "si_physical_timer";
        source = "si_cpu.generic_timer_phys";
        controller = "si_cl0_gic";
        kind = "PPI";
        architectural_intid = 20;
        socket_class = "ppi";
        socket_index = 20;
        trigger = "level";
        polarity = "low";
        owner_view = "View1";
        target_semantics = "per_cpu";
        target_pes = {0, 1, 2, 3, 4};
    };
    {
        name = "si_hypervisor_timer";
        source = "si_cpu.generic_timer_hyp";
        controller = "si_cl0_gic";
        kind = "PPI";
        architectural_intid = 19;
        socket_class = "ppi";
        socket_index = 19;
        trigger = "level";
        polarity = "low";
        owner_view = "View1";
        target_semantics = "per_cpu";
        target_pes = {0, 1, 2, 3, 4};
    };
    {
        name = "si_virtual_timer";
        source = "si_cpu.generic_timer_virt";
        controller = "si_cl0_gic";
        kind = "PPI";
        architectural_intid = 27;
        socket_class = "ppi";
        socket_index = 27;
        trigger = "level";
        polarity = "low";
        owner_view = "View1";
        target_semantics = "per_cpu";
        target_pes = {0, 1, 2, 3, 4};
    };
    {
        name = "si_secure_timer";
        source = "si_cpu.generic_timer_sec";
        controller = "si_cl0_gic";
        kind = "PPI";
        architectural_intid = 29;
        socket_class = "ppi";
        socket_index = 29;
        trigger = "level";
        polarity = "low";
        owner_view = "View1";
        target_semantics = "per_cpu";
        target_pes = {0, 1, 2, 3, 4};
    };
    {
        name = "si_cl0_system_timer";
        source = "si_cl0_timer_cntbase.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 34;
        socket_class = "normal_spi";
        socket_index = 2;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_watchdog_ws0";
        source = "si_cl0_watchdog.ws0";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 37;
        socket_class = "normal_spi";
        socket_index = 5;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl1_uart";
        source = "si_cl1_uart.irq";
        controller = "si_cl1_gic";
        kind = "SPI";
        architectural_intid = 39;
        socket_class = "normal_spi";
        socket_index = 7;
        trigger = "level";
        polarity = "high";
        owner_view = "View2";
        target_semantics = "shared";
        target_pes = {1, 2, 3, 4};
    };
    {
        name = "si_cl0_uart";
        source = "si_cl0_uart.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 40;
        socket_class = "normal_spi";
        socket_index = 8;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl1_hipc_pbx";
        source = "si_cl1_hipc_mhu_pbx.irq";
        controller = "si_cl1_gic";
        kind = "SPI";
        architectural_intid = 72;
        socket_class = "normal_spi";
        socket_index = 40;
        trigger = "level";
        polarity = "high";
        owner_view = "View2";
        target_semantics = "shared";
        target_pes = {1, 2, 3, 4};
    };
    {
        name = "si_cl1_hipc_mbx";
        source = "si_cl1_hipc_mhu_mbx.irq";
        controller = "si_cl1_gic";
        kind = "SPI";
        architectural_intid = 73;
        socket_class = "normal_spi";
        socket_index = 41;
        trigger = "level";
        polarity = "high";
        owner_view = "View2";
        target_semantics = "shared";
        target_pes = {1, 2, 3, 4};
    };
    {
        name = "si_cl1_pfdi";
        source = "si_cl1_pfdi_mhu_pbx.irq";
        controller = "si_cl1_gic";
        kind = "SPI";
        architectural_intid = 82;
        socket_class = "normal_spi";
        socket_index = 50;
        trigger = "level";
        polarity = "high";
        owner_view = "View2";
        target_semantics = "shared";
        target_pes = {1, 2, 3, 4};
    };
    {
        name = "si_cl0_ap_ns_mhu_pbx";
        source = "si_cl0_ap_ns_mhu_pbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 96;
        socket_class = "normal_spi";
        socket_index = 64;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_ap_ns_mhu_mbx";
        source = "si_cl0_ap_ns_mhu_mbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 97;
        socket_class = "normal_spi";
        socket_index = 65;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_ap_scmi_mhu_pbx";
        source = "si_cl0_ap_scmi_mhu_pbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 98;
        socket_class = "normal_spi";
        socket_index = 66;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_ap_scmi_mhu_mbx";
        source = "si_cl0_ap_scmi_mhu_mbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 99;
        socket_class = "normal_spi";
        socket_index = 67;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_ap_pfdi_mhu_pbx";
        source = "si_cl0_ap_pfdi_monitor_mhu_pbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 102;
        socket_class = "normal_spi";
        socket_index = 70;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_ap_pfdi_mhu_mbx";
        source = "si_cl0_ap_pfdi_monitor_mhu_mbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 103;
        socket_class = "normal_spi";
        socket_index = 71;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_rse_mhu";
        source = "si_cl0_rse_mhu_mbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 105;
        socket_class = "normal_spi";
        socket_index = 73;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_cl1_mhu";
        source = "si_cl0_cl1_mhu_mbx.irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 107;
        socket_class = "normal_spi";
        socket_index = 75;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_fmu_critical";
        source = "si_cl0_fmu.critical_irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 128;
        socket_class = "normal_spi";
        socket_index = 96;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
    {
        name = "si_cl0_fmu_noncritical";
        source = "si_cl0_fmu.non_critical_irq";
        controller = "si_cl0_gic";
        kind = "SPI";
        architectural_intid = 129;
        socket_class = "normal_spi";
        socket_index = 97;
        trigger = "level";
        polarity = "high";
        owner_view = "View1";
        target_semantics = "shared";
        target_pes = {0};
    };
}

return {
    schema_version = 1;
    si_active_routes = {
        schema_version = 2;
        routes = SI_ACTIVE_ROUTES;
    };
    irq_routes = {
        { name = "ap_timer_phys"; source = "ap_cpu.generic_timer_phys"; sink = "ap_gic.ppi"; controller = "ap_gic"; kind = "PPI"; id = 30; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_timer_virt"; source = "ap_cpu.generic_timer_virt"; sink = "ap_gic.ppi"; controller = "ap_gic"; kind = "PPI"; id = 27; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_refclk_secure"; source = "ap_timer_mem.frame1"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 48; owner = "smd"; scope = "zena_css_architecture" };
        { name = "ap_refclk_non_secure"; source = "ap_timer_mem.frame0"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 49; owner = "smd"; scope = "zena_css_architecture" };
        { name = "ap_watchdog_ws0"; source = "ap_watchdog_0.ws0"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 50; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_watchdog_ws1"; source = "ap_watchdog_0.ws1"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 51; owner = "smd"; scope = "zena_css_architecture" };
        { name = "ap_secure_watchdog_ws0"; source = "ap_secure_wdog.ws0"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 47; owner = "smd"; scope = "zena_css_architecture" };
        { name = "si_cl0_system_timer"; source = "si_cl0_timer_cntbase"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 34; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_watchdog_ws0"; source = "si_cl0_watchdog.ws0"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 37; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "rse_watchdog_ns_ws0"; source = "rse_watchdog_ns.ws0"; sink = "rse_nvic"; controller = "rse_nvic"; kind = "IRQ"; id = 1; owner = "rse"; scope = "zena_css_architecture" };
        { name = "rse_watchdog_ns_ws1"; source = "rse_watchdog_ns.ws1"; sink = "rse_nvic"; controller = "rse_nvic"; kind = "IRQ"; id = 0; owner = "rse"; scope = "zena_css_architecture" };
        { name = "ap_primary_uart"; source = "ap_primary_uart"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 52; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_secure_uart"; source = "ap_secure_uart"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 53; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_smmu_event"; source = "ap_smmu_0.irq_eventq"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 65; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_ras_ffh"; source = "ap_ras.corrected_deferred"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 89; owner = "ap"; scope = "zena_css_architecture" };
        { name = "ap_si_ns_mhu_pbx"; source = "host_ap_si_ns_scmi_mhu_pbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 112; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_ns_mhu_mbx"; source = "host_ap_si_ns_scmi_mhu_mbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 113; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_scmi_pbx"; source = "host_ap_si_scmi_mhu_pbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 114; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_scmi_mbx"; source = "host_ap_si_scmi_mhu_mbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 115; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_pfdi_pbx"; source = "host_ap_si_pfdi_monitor_mhu_pbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 118; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_pfdi_mbx"; source = "host_ap_si_pfdi_monitor_mhu_mbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 119; owner = "si_cl0"; scope = "rd_aspen_cfg2" };
        { name = "ap_si_hipc_pbx"; source = "host_ap_si_hipc_mhu_pbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 120; owner = "si_cl1"; scope = "fvp_cfg2_extension" };
        { name = "ap_si_hipc_mbx"; source = "host_ap_si_hipc_mhu_mbx"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 121; owner = "si_cl1"; scope = "fvp_cfg2_extension" };
        { name = "gpex_intx_a"; source = "ap_gpex_0.intx0"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 300; owner = "ap"; scope = "rd_aspen_cfg2" };
        { name = "gpex_intx_b"; source = "ap_gpex_0.intx1"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 301; owner = "ap"; scope = "rd_aspen_cfg2" };
        { name = "gpex_intx_c"; source = "ap_gpex_0.intx2"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 302; owner = "ap"; scope = "rd_aspen_cfg2" };
        { name = "gpex_intx_d"; source = "ap_gpex_0.intx3"; sink = "ap_gic.spi"; controller = "ap_gic"; kind = "SPI"; id = 303; owner = "ap"; scope = "rd_aspen_cfg2" };
        { name = "gpex_msi"; source = "ap_gpex_0.msi"; sink = "ap_gic_its.translation"; controller = "ap_gic_its"; kind = "MSI_LPI"; id = 0; owner = "ap"; scope = "zena_css_architecture" };
        { name = "si_cl0_uart"; source = "si_cl0_uart"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 40; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_ns_mhu_pbx"; source = "si_cl0_ap_ns_mhu_pbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 96; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_ns_mhu_mbx"; source = "si_cl0_ap_ns_mhu_mbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 97; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_scmi_mhu_pbx"; source = "si_cl0_ap_scmi_mhu_pbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 98; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_scmi_mhu_mbx"; source = "si_cl0_ap_scmi_mhu_mbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 99; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_pfdi_mhu_pbx"; source = "si_cl0_ap_pfdi_monitor_mhu_pbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 102; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_ap_pfdi_mhu_mbx"; source = "si_cl0_ap_pfdi_monitor_mhu_mbx"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 103; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_fmu_critical"; source = "si_cl0_fmu.critical"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 128; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl0_fmu_noncritical"; source = "si_cl0_fmu.noncritical"; sink = "si_cl0_gic.spi"; controller = "si_cl0_gic"; kind = "SPI"; id = 129; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_cl1_uart"; source = "si_cl1_uart"; sink = "si_cl1_gic.spi"; controller = "si_cl1_gic"; kind = "SPI"; id = 7; owner = "si_cl1"; scope = "fvp_cfg2_extension" };
        { name = "si_cl1_hipc_pbx"; source = "si_cl1_hipc_pbx"; sink = "si_cl1_gic.spi"; controller = "si_cl1_gic"; kind = "SPI"; id = 40; owner = "si_cl1"; scope = "fvp_cfg2_extension" };
        { name = "si_cl1_hipc_mbx"; source = "si_cl1_hipc_mbx"; sink = "si_cl1_gic.spi"; controller = "si_cl1_gic"; kind = "SPI"; id = 41; owner = "si_cl1"; scope = "fvp_cfg2_extension" };
        { name = "si_cl1_pfdi"; source = "si_cl1_pfdi_pbx"; sink = "si_cl1_gic.spi"; controller = "si_cl1_gic"; kind = "SPI"; id = 50; owner = "si_cl0"; scope = "fvp_cfg2_extension" };
        { name = "rse_mhu0"; source = "rse_mhu0_receiver"; sink = "rse_nvic"; controller = "rse_nvic"; kind = "IRQ"; id = 41; owner = "rse"; scope = "zena_css_architecture" };
        { name = "rse_mhu2"; source = "rse_mhu2_receiver"; sink = "rse_nvic"; controller = "rse_nvic"; kind = "IRQ"; id = 45; owner = "rse"; scope = "zena_css_architecture" };
        { name = "rse_si_mhu"; source = "host_rse_si_mhu_mbx"; sink = "rse_nvic"; controller = "rse_nvic"; kind = "IRQ"; id = 139; owner = "rse"; scope = "zena_css_architecture" };
    };
    pcie_irq_test = {
        profile = "QBOX_APOLLO_PCIE_IRQ_TEST";
        endpoint = "virtio-net-pci";
        bdf = "0000:00:01.0";
        device_id = 0x0008;
        stream_id = 0x0040;
        event_id_base = 0;
        event_id_policy = "msi_index";
        its_translator = 0x20850040;
        legacy_intx_spi = 301;
        affinity_cpu = 0;
    };
    reset_routes = {
        { name = "ap_watchdog_to_css_rgm"; source = "ap_watchdog_0.ws1"; sink = "host_reset_ctrl.ap_ns_watchdog_reset"; owner = "smd"; order = 20; scope = "zena_css_architecture" };
        { name = "ap_secure_watchdog_to_css_rgm"; source = "ap_secure_wdog.ws1"; sink = "host_reset_ctrl.ap_s_watchdog_reset"; owner = "smd"; order = 20; scope = "zena_css_architecture" };
        { name = "css_rgm_to_ap_cold_reset"; source = "host_reset_ctrl.ap_reset"; sink = "ap_cold_reset_fanout.reset_in"; owner = "smd"; order = 30; scope = "zena_css_architecture" };
        { name = "rse_swreset_to_apollo_system_reset"; source = "rse_sysctrl.system_reset"; sink = "apollo_system_reset_fanout.reset_in"; owner = "rse"; order = 30; scope = "zena_css_architecture" };
        { name = "si_cl0_watchdog_to_css_rgm"; source = "si_cl0_watchdog.ws1"; sink = "host_reset_ctrl.si_watchdog_reset"; owner = "smd"; order = 20; scope = "zena_css_architecture" };
        { name = "rse_to_ap_primary_reset"; source = "rse_ap_power_request"; sink = "ap_reset_gpio"; owner = "rse"; order = 40; scope = "zena_css_architecture" };
        { name = "si_cl0_to_ap_secondary_reset"; source = "si_cl0_ap_core_ppu.power_on_reset"; sink = "ap_cpu.reset"; owner = "si_cl0"; order = 50; scope = "zena_css_architecture" };
        { name = "qbox_service_model_to_ap_secondary_reset"; source = "host_ap_si_scmi_mhu_pbx.power_domain_reset"; sink = "ap_cpu.reset"; owner = "qbox_service_model"; order = 50; scope = "qbox_compatibility" };
        { name = "si_cl0_cluster_reset"; source = "host_si_cl0_clus_ppu"; sink = "si_cl0_cpu.reset"; owner = "si_cl0"; order = 30; scope = "zena_css_architecture" };
        { name = "si_cl1_cluster_reset"; source = "host_si_cl1_clus_ppu"; sink = "si_cl1_cpu.reset"; owner = "si_cl1"; order = 30; scope = "fvp_cfg2_extension" };
    };
    fault_routes = {
        { name = "si_ni710_apu_to_root_fmu"; source = "si_cl0_ni710ae_primary_nci.apu_fault"; sink = "si_cl0_fmu.record0"; result = "critical_record_and_irq"; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "ap_smmu_event_to_test_fmu_observer"; source = "ap_smmu_0.irq_eventq"; sink = "ap_smmu_fault_observer.record1"; result = "record_and_json_event"; owner = "qbox_test_profile"; enabled_by = "QBOX_APOLLO_FAULT_EVENT_TEST"; scope = "qbox_test_profile" };
        { name = "si_fmu_critical_to_ssu"; source = "si_cl0_fmu.critical"; sink = "si_cl0_ssu"; result = "escalate"; owner = "si_cl0"; scope = "zena_css_architecture" };
        { name = "si_ssu_to_rgm"; source = "si_cl0_ssu.safety_status"; sink = "host_reset_ctrl.safety_fault_reset"; result = "syndrome_and_masked_ap_reset"; owner = "smd"; scope = "zena_css_architecture" };
        { name = "ap_ras_to_ffh"; source = "ap_ras"; sink = "tfa_ffh"; result = "spi_89_and_notification"; owner = "ap"; scope = "zena_css_architecture" };
    };
}
