add_subdirectory(gicx00_multiview)
add_subdirectory(apollo_runtime_injection)
add_subdirectory(gic720ae_messreg)
add_subdirectory(apollo_sbist)
add_subdirectory(apollo_cpu_ras)
add_subdirectory(arm_system_counter)
add_subdirectory(host_cmn_cyprus)
add_subdirectory(host_gtimer)
add_subdirectory(host_ni710ae_nci)
add_subdirectory(host_ppu)
add_subdirectory(host_smcf_mgi)
add_subdirectory(host_system_pll)
add_subdirectory(zena_fmu)
add_subdirectory(zena_device_fmu)
add_subdirectory(zena_ni710ae_fmu)
add_subdirectory(zena_ssu)
add_subdirectory(zena_watchdog)
add_subdirectory(zena_reset_ctrl)
add_subdirectory(signal_fanout)
add_subdirectory(signal_or)
add_subdirectory(reset_fanout)
add_subdirectory(rse_protection_ctrl)
add_subdirectory(rse_ppc_filter)
add_subdirectory(strata_flash_j3)
add_subdirectory(mhu320ae)
add_subdirectory(ras_ffh_stub)
add_subdirectory(mmu720ae)
add_subdirectory(cc3xx)
add_subdirectory(dma350)
add_subdirectory(dw-apb-i2s)
add_subdirectory(host_scr)
add_subdirectory(hsoc_gpio)
add_subdirectory(rse_atu)
add_subdirectory(rse_integrity_checker)
add_subdirectory(rse_kmu)
add_subdirectory(rse_lcm)
add_subdirectory(rse_sam)
add_subdirectory(rse_sysctrl)
