add_subdirectory(gicx00_multiview)
add_subdirectory(host_cmn_cyprus)
add_subdirectory(host_gtimer)
add_subdirectory(host_ni710ae_nci)
add_subdirectory(host_ppu)
add_subdirectory(host_smcf_mgi)
add_subdirectory(host_system_pll)
add_subdirectory(zena_fmu)
add_subdirectory(zena_ssu)
add_subdirectory(reset_fanout)
add_subdirectory(rse_protection_ctrl)
add_subdirectory(strata_flash_j3)
add_subdirectory(mhuv3_stub)
add_subdirectory(mhuv3_rproc_stub)
add_subdirectory(mhu320ae)
add_subdirectory(ras_ffh_stub)
add_subdirectory(mmu720ae)
add_subdirectory(cc3xx)
add_subdirectory(dma350)
add_subdirectory(host_scr)
add_subdirectory(rse_atu)
add_subdirectory(rse_integrity_checker)
add_subdirectory(rse_kmu)
add_subdirectory(rse_lcm)
add_subdirectory(rse_sam)
add_subdirectory(rse_sysctrl)
