macro(gs_add_test test)
    set(test_target "apollo-${test}")
    add_executable(${test_target} ${test}.cc)
    target_link_libraries(${test_target} PRIVATE gtest gmock uart-pl011 uart-ibex char_backend_socket char_backend_file char_backend_stdio ${TARGET_LIBS})
    if (WIN32)
        target_link_libraries(${test_target} PRIVATE ws2_32)
    endif()
    add_test(NAME ${test_target} COMMAND ${test_target})
    set_tests_properties(${test_target} PROPERTIES
        TIMEOUT 30 LABELS "qbox-platform-uart")
endmacro()
gs_add_test(file-backend-test)
gs_add_test(pl011-aperture-tests)
gs_add_test(uart-biflow-stdio-test)
gs_add_test(uart-biflow-backend-socket-test)
gs_add_test(uart-ibex-biflow-stdio-test)
