add_subdirectory(exclusive-monitor)
add_subdirectory(memory)
add_subdirectory(router)
add_subdirectory(router-memory)
add_subdirectory(addrtr)
add_subdirectory(aliases)
add_subdirectory(loader)
add_subdirectory(memory-blocs)
add_subdirectory(dmi-converter)
add_subdirectory(remote)
if(ENABLE_PYTHON_BINDER AND (NOT GS_ONLY))
    add_subdirectory(python-binder)
endif()
add_subdirectory(gs_register)
add_subdirectory(generic_lua_model)
add_subdirectory(container_builder)

if(NOT WIN32)
    add_subdirectory(fss)
endif()
add_subdirectory(uart)
add_subdirectory(cc3xx)
add_subdirectory(dma350)
add_subdirectory(mhu320ae)
add_subdirectory(gicx00_multiview)
add_subdirectory(gic720ae_messreg)
add_subdirectory(apollo_sbist)
add_subdirectory(apollo_cpu_ras)
add_subdirectory(mmu720ae)
add_subdirectory(host_cmn_cyprus)
add_subdirectory(host_gtimer)
add_subdirectory(host_ni710ae_nci)
add_subdirectory(host_ppu)
add_subdirectory(host_scr)
add_subdirectory(host_smcf_mgi)
add_subdirectory(host_system_pll)
add_subdirectory(ras_ffh_stub)
add_subdirectory(zena_fmu)
add_subdirectory(zena_ssu)
add_subdirectory(zena_watchdog)
add_subdirectory(zena_reset_ctrl)
add_subdirectory(zena_safety_vertical)
add_subdirectory(reset_fanout)
add_subdirectory(rse_protection_ctrl)
add_subdirectory(rse_atu)
add_subdirectory(rse_integrity_checker)
add_subdirectory(rse_kmu)
add_subdirectory(rse_lcm)
add_subdirectory(rse_sam)
add_subdirectory(rse_sysctrl)
add_subdirectory(strata_flash_j3)
